title: iWish Gifts Blog
email: suporte@iwish.gifts
description: Aqui você saberá de tudo sobre como organizar e montar chás de bebe, chá de fralda, chá revelação
baseurl: "" 
url: "https://blog.iwish.gifts

# Configurações do Autor
author:
  name: "iWish Gifts"
  github_username: gcouti

# Configurações de Build
# theme: minima # O GitHub Pages já vem com o tema 'minima' instalado por padrão
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme 

# Configurações de Markdown
markdown: kramdown
highlighter: rouge # Para destacar código de programação com cores

# Excluir arquivos que não precisam ser processados
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
